version: '3'

services: 

    fastapi-todo:
        restart: unless-stopped
        build: ./backend
        container_name: fastapi-todo
        entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"
        volumes:
            - './backend:/app'
        depends_on:
            - todo-db

    todo-db:
        restart: always
        image: postgres:13
        container_name: todo-db
        expose:
            - "5432"
        environment:
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=user
            - POSTGRES_DB=db